name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Lint README.md
      uses: docker://avtodev/markdown-lint:v1
      with:
        rules: '/lint/rules/changelog.js'
        config: '/github/workspace/.changelog.yml'
        args: './README.md'
