name: Convert README.md to Downloadable Resume

on:
  push:
    branches: [ master ]

jobs:
  convert_to_pdf: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Create PDF
      uses: Ender-events/pandoc@master
      with:
        args: "-s -o resume.pdf README.md"
    - name: Upload PDF
      uses: actions/upload-artifact@master
      with:
        name: /download/resume.pdf
        path: resume.pdf
  convert_to_docx: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Create .docx
      uses: docker://pandoc/core:2.9
      with:
        args: "-o resume.docx README.md"
    - name: Upload .docx
      uses: actions/upload-artifact@master
      with:
        name: /download/resume.docx
        path: resume.docx
